version: '3.1'

volumes:
  pg_data:

networks:
  hw-net:
    driver: bridge

services:

  hw-postgresql:
    container_name: hw-postgresql
    image: hw-postgresql
    build:
      context: ./docker-images/postgresql/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORTS}
    restart: always
    networks:
      - hw-net
    volumes:
      - pg_data:/hw/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
